spring:
  application:
    name: eureka

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false #表示是否注册自身到eureka服务器,因为当前这个应用就是eureka服务器,没必要注册自身,所以这里是false
    fetchRegistry: false #表示是否从eureka服务器获取注册信息，同上，这里不需要
  server:
    waitTimeInMsWhenSyncEmpty: 0 # 设置同步为空时的等待时间。默认 5 * MINUTES